apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
    name: <domain>-tls
spec:
    secretName: <domain>
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: <domain>
    dnsNames:
        - <domain>
        - www.<domain>
    acme:
        config:
            - http01:
                ingressClass: nginx
              domains:
                - <domain>
                - www.<domain>